import AsyncStorage from "@react-native-async-storage/async-storage";
import { Platform } from "react-native";
import * as Notifications from "expo-notifications";
import type { Contact } from "./types";
import { generateReminders } from "./reminders";
import type { Reminder } from "./reminders";
import { loadSchedulerData, getDaysSinceLastSuggestedSync, scoreSuggestion } from "./suggestion-scheduler";
import { getDaysSince, getDaysUntilBirthday } from "./helpers";
import { getSmartPrompt, getActionType } from "./prompts";

const REMINDER_NOTIFS_KEY = "bridges_reminder_notifs_v1";
const SUGGESTION_NUDGE_KEY = "bridges_suggestion_nudge_v2";
const MAX_REMINDER_NOTIFS = 10;

interface ReminderNotifEntry {
  notifId: string;
  scheduledFor: string;
}

interface SuggestionNudgeEntry {
  notifId: string;
  scheduledFor: string;
  topContactId: string | null;
}

// Returns the next 9am. If it's already past 9am today, returns tomorrow at 9am.
function nextNineAm(): Date {
  const now = new Date();
  const target = new Date(now);
  target.setHours(9, 0, 0, 0);
  if (target <= now) {
    target.setDate(target.getDate() + 1);
  }
  return target;
}

// Returns the next occurrence of preferredHour:00. If already past today, returns tomorrow.
function nextPreferredTime(preferredHour: number): Date {
  const now = new Date();
  const target = new Date(now);
  target.setHours(preferredHour, 0, 0, 0);
  if (target <= now) {
    target.setDate(target.getDate() + 1);
  }
  return target;
}

// "2026-06-30T09" — hour-level granularity for dedup comparisons
function hourKey(date: Date): string {
  return date.toISOString().slice(0, 13);
}

async function loadReminderEntries(): Promise<Record<string, ReminderNotifEntry>> {
  try {
    const raw = await AsyncStorage.getItem(REMINDER_NOTIFS_KEY);
    return raw ? (JSON.parse(raw) as Record<string, ReminderNotifEntry>) : {};
  } catch {
    return {};
  }
}

async function saveReminderEntries(entries: Record<string, ReminderNotifEntry>): Promise<void> {
  try {
    await AsyncStorage.setItem(REMINDER_NOTIFS_KEY, JSON.stringify(entries));
  } catch {}
}

async function cancelNotif(notifId: string): Promise<void> {
  try {
    await Notifications.cancelScheduledNotificationAsync(notifId);
  } catch {}
}

interface LocalNotifMessage {
  id: string;
  title: string;
  body: string;
  contactId?: string;
}

/** Map a Reminder (as generated by lib/reminders.ts) to a local notification message. */
function reminderToNotifMessage(reminder: Reminder): LocalNotifMessage | null {
  // Skip profile-completion reminders — they don't make sense as device notifications
  if (
    reminder.type === "profile-completion-high" ||
    reminder.type === "profile-completion-medium" ||
    reminder.type === "profile-completion-low"
  ) {
    return null;
  }

  return {
    id: `local-${reminder.id}`,
    title: reminder.title,
    body: reminder.subtitle || reminder.title,
    contactId: reminder.contactId,
  };
}

// Module-level serialization: ensures concurrent callers don't race on the
// AsyncStorage read-then-write inside scheduleReminderNotifications.
let reminderScheduleInFlight: Promise<void> | null = null;

/**
 * Schedules local notifications for all active reminders (birthday milestones,
 * custom date reminders, overdue check-ins, overdue hangouts). Derives notifications
 * from the same logic as generateReminders() in lib/reminders.ts so thresholds are
 * always in sync. Mirrors the elevation pattern: deduplicates via AsyncStorage,
 * caps at MAX_REMINDER_NOTIFS, cancels stale entries. No-ops on web.
 *
 * Concurrent calls are serialized: if a call is already in progress, the new call
 * waits for it to finish and then runs itself so it uses the freshest contacts data.
 */
export async function scheduleReminderNotifications(contacts: Contact[]): Promise<void> {
  if (Platform.OS === "web") return;

  // If there's already a scheduling run in progress, wait for it to finish first,
  // then run ourselves (do NOT skip — we may carry newer contacts data).
  if (reminderScheduleInFlight) {
    await reminderScheduleInFlight;
  }

  let resolve!: () => void;
  reminderScheduleInFlight = new Promise<void>((res) => { resolve = res; });
  try {
    await _scheduleReminderNotificationsImpl(contacts);
  } finally {
    reminderScheduleInFlight = null;
    resolve();
  }
}

async function _scheduleReminderNotificationsImpl(contacts: Contact[]): Promise<void> {

  const targetTime = nextNineAm();
  const targetHour = hourKey(targetTime);
  const existing = await loadReminderEntries();

  // Generate all active reminders using the same engine as the home screen
  const allReminders: Reminder[] = generateReminders(contacts);

  // Map reminders → notification messages, drop profile-completion entries
  const wanted: LocalNotifMessage[] = [];
  for (const reminder of allReminders) {
    const msg = reminderToNotifMessage(reminder);
    if (msg) wanted.push(msg);
  }

  // Cap at iOS 64 limit — take highest-priority reminders (generateReminders already sorts descending)
  const toSchedule = wanted.slice(0, MAX_REMINDER_NOTIFS);
  const wantedIds = new Set(toSchedule.map((m) => m.id));

  // Cancel notifications that are no longer active
  for (const [id, entry] of Object.entries(existing)) {
    if (!wantedIds.has(id)) {
      await cancelNotif(entry.notifId);
      delete existing[id];
    }
  }

  // Schedule new or rescheduled notifications
  for (const msg of toSchedule) {
    const prev = existing[msg.id];
    if (prev && prev.scheduledFor.slice(0, 13) === targetHour) {
      continue; // Already scheduled for this hour window — skip
    }
    if (prev) {
      await cancelNotif(prev.notifId);
    }
    try {
      const notifId = await Notifications.scheduleNotificationAsync({
        content: {
          title: msg.title,
          body: msg.body,
          sound: true,
          data: msg.contactId ? { contactId: msg.contactId } : {},
        },
        trigger: {
          type: Notifications.SchedulableTriggerInputTypes.DATE,
          date: targetTime,
        },
      });
      existing[msg.id] = { notifId, scheduledFor: targetTime.toISOString() };
    } catch {}
  }

  await saveReminderEntries(existing);
}

// Serialization lock for scheduleSuggestionNudge — same pattern as reminder
// scheduling to prevent duplicate notifications when multiple tabs mount simultaneously.
let nudgeScheduleInFlight: Promise<void> | null = null;

/**
 * Schedules (or cancels) the daily suggestion nudge local notification.
 * Fires at 9am (morning) or 5pm (afternoon) based on user preference.
 * Personalized with the top-scored suggestion contact's name when contacts are provided.
 * Skips if already scheduled for the same hour slot. No-ops on web.
 *
 * Only call this from ONE place (index.tsx) to avoid duplicate notifications.
 * Concurrent calls are serialized via nudgeScheduleInFlight.
 */
export async function scheduleSuggestionNudge(
  frequency: string | null | undefined,
  preferredTime: string | null | undefined,
  contacts?: Contact[],
): Promise<void> {
  if (Platform.OS === "web") return;

  // Serialize concurrent calls — both tabs used to call this simultaneously,
  // causing a read-before-write race that produced two notifications.
  if (nudgeScheduleInFlight) {
    await nudgeScheduleInFlight;
    return; // Let the first caller do the work; subsequent callers skip.
  }

  let resolve!: () => void;
  nudgeScheduleInFlight = new Promise<void>((res) => { resolve = res; });
  try {
    await _scheduleSuggestionNudgeImpl(frequency, preferredTime, contacts);
  } finally {
    nudgeScheduleInFlight = null;
    resolve();
  }
}

async function _scheduleSuggestionNudgeImpl(
  frequency: string | null | undefined,
  preferredTime: string | null | undefined,
  contacts?: Contact[],
): Promise<void> {
  if (!frequency || frequency === "off") {
    const raw = await AsyncStorage.getItem(SUGGESTION_NUDGE_KEY);
    if (raw) {
      try {
        const entry = JSON.parse(raw) as SuggestionNudgeEntry;
        await cancelNotif(entry.notifId);
      } catch {}
      await AsyncStorage.removeItem(SUGGESTION_NUDGE_KEY).catch(() => {});
    }
    return;
  }

  const preferredHour = preferredTime === "afternoon" ? 17 : 9;
  const targetTime = nextPreferredTime(preferredHour);
  const targetHour = hourKey(targetTime);

  // Pick the top-scored contact to personalize the notification.
  // Do this BEFORE the dedup check so we can compare against the stored contact.
  let topContact: Contact | null = null;
  if (contacts && contacts.length > 0) {
    const lastSuggestedDates = await loadSchedulerData();
    let best = -Infinity;
    for (const c of contacts) {
      if (!c.circleLevel || c.circleLevel < 1 || c.circleLevel > 3) continue;
      const cl = c.circleLevel as 1 | 2 | 3;
      const daysSinceSug = getDaysSinceLastSuggestedSync(c.id, lastSuggestedDates);
      const daysSinceContact = getDaysSince(c.lastContacted ?? undefined);
      const daysUntilBday = getDaysUntilBirthday(c.birthday ?? undefined);
      const score = scoreSuggestion(cl, daysSinceSug, daysSinceContact, daysUntilBday);
      if (score > best) {
        best = score;
        topContact = c;
      }
    }
  }

  // Dedup: skip rescheduling only if the same hour AND the same top contact.
  // If the stored entry was generic (no topContactId) but we now have a real
  // contact, or the top contact changed, cancel and reschedule with fresh copy.
  const raw = await AsyncStorage.getItem(SUGGESTION_NUDGE_KEY);
  if (raw) {
    try {
      const entry = JSON.parse(raw) as SuggestionNudgeEntry;
      const sameHour = entry.scheduledFor.slice(0, 13) === targetHour;
      const sameContact = entry.topContactId === (topContact?.id ?? null);
      if (sameHour && sameContact) {
        return; // Already scheduled with the right person for the right slot
      }
      await cancelNotif(entry.notifId);
    } catch {}
  }

  let title = "Time to reach out";
  let body = "Open Bridges to see today's suggestion.";

  if (topContact) {
    const firstName = topContact.name.split(" ")[0];
    const cl = topContact.circleLevel as 1 | 2 | 3;
    try {
      const prompt = getSmartPrompt(
        topContact.id,
        topContact.name,
        cl,
        topContact.interests ?? [],
        { labels: topContact.labels ?? [] },
      );
      let actionType = getActionType(cl, prompt);
      // C3 calls → text; hangout doesn't translate well to a notification CTA
      if (cl === 3 && actionType === "call") actionType = "text";
      if (actionType === "hangout") actionType = "text";

      title = actionType === "call" ? `Call ${firstName}` : `Text ${firstName}`;

      // Trim prompt to ~130 chars so the suffix fits comfortably in the banner
      const suffix = " Open Bridges for more suggestions.";
      const maxPromptLen = 160 - suffix.length;
      const trimmedPrompt = prompt.length > maxPromptLen
        ? prompt.slice(0, maxPromptLen - 1).trimEnd() + "…"
        : prompt;
      body = `${trimmedPrompt}${suffix}`;
    } catch {
      title = `Time to reach out to ${firstName}`;
      body = `${firstName} is your top suggestion today. Open Bridges for more.`;
    }
  }

  try {
    const notifId = await Notifications.scheduleNotificationAsync({
      content: {
        title,
        body,
        sound: true,
        data: topContact ? { contactId: topContact.id } : {},
      },
      trigger: {
        type: Notifications.SchedulableTriggerInputTypes.DATE,
        date: targetTime,
      },
    });
    const entry: SuggestionNudgeEntry = { notifId, scheduledFor: targetTime.toISOString(), topContactId: topContact?.id ?? null };
    await AsyncStorage.setItem(SUGGESTION_NUDGE_KEY, JSON.stringify(entry));
  } catch {}
}
