import AsyncStorage from "@react-native-async-storage/async-storage";
import { Platform } from "react-native";
import * as Notifications from "expo-notifications";
import type { Contact } from "./types";
import { generateReminders } from "./reminders";
import type { Reminder } from "./reminders";

const REMINDER_NOTIFS_KEY = "bridges_reminder_notifs_v1";
const SUGGESTION_NUDGE_KEY = "bridges_suggestion_nudge_v1";
const MAX_REMINDER_NOTIFS = 10;

interface ReminderNotifEntry {
  notifId: string;
  scheduledFor: string;
}

interface SuggestionNudgeEntry {
  notifId: string;
  scheduledFor: string;
}

// Returns the next 9am. If it's already past 9am today, returns tomorrow at 9am.
function nextNineAm(): Date {
  const now = new Date();
  const target = new Date(now);
  target.setHours(9, 0, 0, 0);
  if (target <= now) {
    target.setDate(target.getDate() + 1);
  }
  return target;
}

// Returns the next occurrence of preferredHour:00. If already past today, returns tomorrow.
function nextPreferredTime(preferredHour: number): Date {
  const now = new Date();
  const target = new Date(now);
  target.setHours(preferredHour, 0, 0, 0);
  if (target <= now) {
    target.setDate(target.getDate() + 1);
  }
  return target;
}

// "2026-06-30T09" — hour-level granularity for dedup comparisons
function hourKey(date: Date): string {
  return date.toISOString().slice(0, 13);
}

async function loadReminderEntries(): Promise<Record<string, ReminderNotifEntry>> {
  try {
    const raw = await AsyncStorage.getItem(REMINDER_NOTIFS_KEY);
    return raw ? (JSON.parse(raw) as Record<string, ReminderNotifEntry>) : {};
  } catch {
    return {};
  }
}

async function saveReminderEntries(entries: Record<string, ReminderNotifEntry>): Promise<void> {
  try {
    await AsyncStorage.setItem(REMINDER_NOTIFS_KEY, JSON.stringify(entries));
  } catch {}
}

async function cancelNotif(notifId: string): Promise<void> {
  try {
    await Notifications.cancelScheduledNotificationAsync(notifId);
  } catch {}
}

interface LocalNotifMessage {
  id: string;
  title: string;
  body: string;
  contactId?: string;
}

/** Map a Reminder (as generated by lib/reminders.ts) to a local notification message. */
function reminderToNotifMessage(reminder: Reminder): LocalNotifMessage | null {
  // Skip profile-completion reminders — they don't make sense as device notifications
  if (
    reminder.type === "profile-completion-high" ||
    reminder.type === "profile-completion-medium" ||
    reminder.type === "profile-completion-low"
  ) {
    return null;
  }

  return {
    id: `local-${reminder.id}`,
    title: reminder.title,
    body: reminder.subtitle || reminder.title,
    contactId: reminder.contactId,
  };
}

/**
 * Schedules local notifications for all active reminders (birthday milestones,
 * custom date reminders, overdue check-ins, overdue hangouts). Derives notifications
 * from the same logic as generateReminders() in lib/reminders.ts so thresholds are
 * always in sync. Mirrors the elevation pattern: deduplicates via AsyncStorage,
 * caps at MAX_REMINDER_NOTIFS, cancels stale entries. No-ops on web.
 */
export async function scheduleReminderNotifications(contacts: Contact[]): Promise<void> {
  if (Platform.OS === "web") return;

  const targetTime = nextNineAm();
  const targetHour = hourKey(targetTime);
  const existing = await loadReminderEntries();

  // Generate all active reminders using the same engine as the home screen
  const allReminders: Reminder[] = generateReminders(contacts);

  // Map reminders → notification messages, drop profile-completion entries
  const wanted: LocalNotifMessage[] = [];
  for (const reminder of allReminders) {
    const msg = reminderToNotifMessage(reminder);
    if (msg) wanted.push(msg);
  }

  // Cap at iOS 64 limit — take highest-priority reminders (generateReminders already sorts descending)
  const toSchedule = wanted.slice(0, MAX_REMINDER_NOTIFS);
  const wantedIds = new Set(toSchedule.map((m) => m.id));

  // Cancel notifications that are no longer active
  for (const [id, entry] of Object.entries(existing)) {
    if (!wantedIds.has(id)) {
      await cancelNotif(entry.notifId);
      delete existing[id];
    }
  }

  // Schedule new or rescheduled notifications
  for (const msg of toSchedule) {
    const prev = existing[msg.id];
    if (prev && prev.scheduledFor.slice(0, 13) === targetHour) {
      continue; // Already scheduled for this hour window — skip
    }
    if (prev) {
      await cancelNotif(prev.notifId);
    }
    try {
      const notifId = await Notifications.scheduleNotificationAsync({
        content: {
          title: msg.title,
          body: msg.body,
          sound: true,
          data: msg.contactId ? { contactId: msg.contactId } : {},
        },
        trigger: {
          type: Notifications.SchedulableTriggerInputTypes.DATE,
          date: targetTime,
        },
      });
      existing[msg.id] = { notifId, scheduledFor: targetTime.toISOString() };
    } catch {}
  }

  await saveReminderEntries(existing);
}

/**
 * Schedules (or cancels) the daily suggestion nudge local notification.
 * Fires at 9am (morning) or 5pm (afternoon) based on user preference.
 * Skips if already scheduled for the same hour slot. No-ops on web.
 */
export async function scheduleSuggestionNudge(
  frequency: string | null | undefined,
  preferredTime: string | null | undefined,
): Promise<void> {
  if (Platform.OS === "web") return;

  if (!frequency || frequency === "off") {
    const raw = await AsyncStorage.getItem(SUGGESTION_NUDGE_KEY);
    if (raw) {
      try {
        const entry = JSON.parse(raw) as SuggestionNudgeEntry;
        await cancelNotif(entry.notifId);
      } catch {}
      await AsyncStorage.removeItem(SUGGESTION_NUDGE_KEY).catch(() => {});
    }
    return;
  }

  const preferredHour = preferredTime === "afternoon" ? 17 : 9;
  const targetTime = nextPreferredTime(preferredHour);
  const targetHour = hourKey(targetTime);

  const raw = await AsyncStorage.getItem(SUGGESTION_NUDGE_KEY);
  if (raw) {
    try {
      const entry = JSON.parse(raw) as SuggestionNudgeEntry;
      if (entry.scheduledFor.slice(0, 13) === targetHour) {
        return; // Already scheduled for the right slot
      }
      await cancelNotif(entry.notifId);
    } catch {}
  }

  try {
    const notifId = await Notifications.scheduleNotificationAsync({
      content: {
        title: "Time to reach out",
        body: "Open Bridges to see today's suggestion.",
        sound: true,
        data: {},
      },
      trigger: {
        type: Notifications.SchedulableTriggerInputTypes.DATE,
        date: targetTime,
      },
    });
    const entry: SuggestionNudgeEntry = { notifId, scheduledFor: targetTime.toISOString() };
    await AsyncStorage.setItem(SUGGESTION_NUDGE_KEY, JSON.stringify(entry));
  } catch {}
}
