/**
 * Profile completion card tests.
 *
 * Profile completion cards are generated by generateProfileCompletionReminders()
 * and surfaced through the bell icon (BellSheet) — they are NOT part of the main
 * reminders list anymore. Tests 1-12 verify the card logic directly. Tests 13-20
 * verify that the bell-sheet source function produces the same cards under the
 * same conditions (they are structurally identical — same function, different caller).
 */
import { generateProfileCompletionReminders, generateReminders } from "../lib/reminders";
import type { Contact } from "../lib/types";

let passed = 0;
let failed = 0;

function assert(condition: boolean, message: string) {
  if (condition) {
    console.log(`  ✓ ${message}`);
    passed++;
  } else {
    console.error(`  ✗ FAIL: ${message}`);
    failed++;
  }
}

function makeContact(overrides: Partial<Contact> & { id: string; circleLevel: number }): Contact {
  return {
    name: "Test",
    interests: [],
    labels: [],
    avatarColor: "#aaa",
    lastContacted: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    ...overrides,
  };
}

console.log("\n=== Profile Completion Card Tests (bell-icon source function) ===\n");

// ─── Test 1: Red card (C1 no birthday) ───
console.log("Test 1: Red card appears when a Circle 1 contact has no birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: undefined, labels: ["College Friend"], interests: ["Reading"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "05/01", labels: ["Work Friend"], interests: ["Gaming"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const redCard = reminders.find((r) => r.type === "profile-completion-high");
  assert(!!redCard, "Red card appears when C1 contact has no birthday");
  assert(redCard?.title === "Add birthdays to your Core contacts to unlock reminders.", "Red card has correct title");
}

console.log("\nTest 2: Red card disappears after adding C1 birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "06/15", labels: ["College Friend"], interests: ["Reading"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "05/01", labels: ["Work Friend"], interests: ["Gaming"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const redCard = reminders.find((r) => r.type === "profile-completion-high");
  assert(!redCard, "Red card disappears when C1 contact gets a birthday");
}

// ─── Test 3: Orange card (C2 no birthday) ───
console.log("\nTest 3: Orange card appears when a Circle 2 contact has no birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: undefined, labels: ["Work Friend"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "08/10", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const orangeCard = reminders.find((r) => r.type === "profile-completion-medium");
  assert(!!orangeCard, "Orange card appears when C2 contact has no birthday");
  assert(
    orangeCard?.title === "Some close contacts are missing birthdays or interests.",
    "Orange card has correct title"
  );
}

console.log("\nTest 4: Orange card disappears after adding C2 birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "05/12", labels: ["Work Friend"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "08/10", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const orangeCard = reminders.find((r) => r.type === "profile-completion-medium");
  assert(!orangeCard, "Orange card disappears when C2 contact gets a birthday");
}

// ─── Test 5: Orange card (C1/C2 missing interests) ───
console.log("\nTest 5: Orange card appears when a Circle 1/2 contact has no interests");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: [], interests: [] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Gaming"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const orangeCard = reminders.find((r) => r.type === "profile-completion-medium");
  assert(!!orangeCard, "Orange card appears when C1 contact has no interests");
}

console.log("\nTest 6: Orange card disappears after adding interests to C1 contact");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: [], interests: ["Cooking"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Gaming"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const orangeCard = reminders.find((r) => r.type === "profile-completion-medium");
  assert(!orangeCard, "Orange card disappears when C1 contact gets interests");
}

// ─── Test 7: Yellow card (C3 no birthday) ───
console.log("\nTest 7: Yellow card appears when a Circle 3 contact has no birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: undefined, labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const yellowCard = reminders.find((r) => r.type === "profile-completion-low");
  assert(!!yellowCard, "Yellow card appears when C3 contact has no birthday");
  assert(
    yellowCard?.title?.startsWith("Some contacts are missing birthdays"),
    "Yellow card has correct title"
  );
}

console.log("\nTest 8: Yellow card disappears after all C3 contacts get birthdays");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const yellowCard = reminders.find((r) => r.type === "profile-completion-low");
  assert(!yellowCard, "Yellow card disappears when all C3 contacts have birthdays");
}

// ─── Test 9: Yellow card (any contact missing interests) ───
console.log("\nTest 9: Yellow card appears when any contact has no interests");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: [] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const yellowCard = reminders.find((r) => r.type === "profile-completion-low");
  assert(!!yellowCard, "Yellow card appears when any contact (including C2) has no interests");
}

console.log("\nTest 10: Yellow card disappears after the contact gets interests");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Music"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  const yellowCard = reminders.find((r) => r.type === "profile-completion-low");
  assert(!yellowCard, "Yellow card disappears when all contacts have interests");
}

// ─── Test 11: No cards when all data is complete ───
console.log("\nTest 11: No profile completion cards when all data is complete");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["College Friend"], interests: ["Fitness"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work Friend"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const reminders = generateProfileCompletionReminders(contacts);
  assert(reminders.length === 0, "No profile completion cards when all contacts have complete data");
}

// ─── Test 12: No cards with empty contact list ───
console.log("\nTest 12: No profile completion cards with zero contacts");
{
  const reminders = generateProfileCompletionReminders([]);
  assert(reminders.length === 0, "No profile completion cards with zero contacts");
}

// ─── Test 13: Profile completion cards do NOT appear in generateReminders ───
console.log("\nTest 13: Profile completion cards are absent from generateReminders (home/suggestions feed)");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: undefined, labels: [], interests: [] }),
  ];
  const reminders = generateReminders(contacts);
  const pcCards = reminders.filter((r) => r.type.startsWith("profile-completion"));
  assert(pcCards.length === 0, "generateReminders contains no profile-completion cards");
}

// ─── Tests 14-20: card dismiss logic via generateProfileCompletionReminders ───

function bellReminders(
  contacts: Contact[],
  dismissedIds: Set<string> = new Set(),
) {
  return generateProfileCompletionReminders(contacts).filter((r) => !dismissedIds.has(r.id));
}

console.log("\nTest 14: Red card disappears from bell list after C1 birthday is added");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["Family"], interests: ["Reading"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "05/01", labels: ["Work"], interests: ["Gaming"] }),
  ];
  const card = bellReminders(contacts).find((r) => r.type === "profile-completion-high");
  assert(!card, "Red card disappears from bell list once C1 contact has a birthday");
}

console.log("\nTest 15: Orange card appears in bell list when C2 has no birthday");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["Family"], interests: ["Running"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: undefined, labels: ["Work"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const card = bellReminders(contacts).find((r) => r.type === "profile-completion-medium");
  assert(!!card, "Orange card appears in bell list when C2 contact is missing a birthday");
}

console.log("\nTest 16: Orange card disappears from bell list after C2 birthday is added");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["Family"], interests: ["Running"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work"], interests: ["Gaming"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const card = bellReminders(contacts).find((r) => r.type === "profile-completion-medium");
  assert(!card, "Orange card disappears from bell list once C2 contact has a birthday");
}

console.log("\nTest 17: Yellow card appears in bell list when any contact is missing interests");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["Family"], interests: ["Running"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work"], interests: [] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const card = bellReminders(contacts).find((r) => r.type === "profile-completion-low");
  assert(!!card, "Yellow card appears in bell list when any contact lacks interests");
}

console.log("\nTest 18: Yellow card disappears from bell list after enrichment is added");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: "03/15", labels: ["Family"], interests: ["Running"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "07/04", labels: ["Work"], interests: ["Music"] }),
    makeContact({ id: "c3", circleLevel: 3, birthday: "11/22", labels: ["Neighbor"], interests: ["Movies"] }),
  ];
  const card = bellReminders(contacts).find((r) => r.type === "profile-completion-low");
  assert(!card, "Yellow card disappears from bell list once all contacts have interests");
}

console.log("\nTest 19: Dismissed profile-completion-high card is hidden");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: undefined, labels: ["Family"], interests: ["Reading"] }),
  ];
  const before = bellReminders(contacts);
  assert(!!before.find((r) => r.type === "profile-completion-high"), "Red card visible before dismiss");
  const after = bellReminders(contacts, new Set(["profile-completion-high"]));
  assert(!after.find((r) => r.type === "profile-completion-high"), "Red card hidden after dismiss");
}

console.log("\nTest 20: Red card appears when C1 has no birthday, absent when C2 is the only issue");
{
  const contacts: Contact[] = [
    makeContact({ id: "c1", circleLevel: 1, birthday: undefined, labels: ["Family"], interests: ["Reading"] }),
    makeContact({ id: "c2", circleLevel: 2, birthday: "05/01", labels: ["Work"], interests: ["Gaming"] }),
  ];
  const cards = bellReminders(contacts);
  assert(!!cards.find((r) => r.type === "profile-completion-high"), "Red card present when C1 missing birthday");
  assert(!cards.find((r) => r.type === "profile-completion-medium"), "Orange card absent when C2 has birthday");
}

// ─── Summary ───
console.log(`\n=== Results: ${passed} passed, ${failed} failed ===\n`);
if (failed > 0) process.exit(1);
